In [3]:
import numpy as np 

In [19]:
a=np.array([1,2,3],dtype='int32')
print(a)

[1 2 3]


In [6]:
b=np.array([[9.0,8.0,7.0],[5.0,4.0,6.0]])
print(b)

[[9. 8. 7.]
 [5. 4. 6.]]


In [7]:
# get dimantion
b.ndim

2

In [8]:
# get shape
b.shape

(2, 3)

In [9]:
# get type
b.dtype

dtype('float64')

In [20]:
# get size
a.itemsize

4

In [22]:
# get total siz
b.size

6

**Accessing/Changing specific elements, rows, columns, etc**


In [24]:
a=np.array([[1,3,5,7,9],[2,4,6,8,10]])
print(a)

[[ 1  3  5  7  9]
 [ 2  4  6  8 10]]


In [29]:
#get spesific elemant 
a[1,3]

8

In [30]:
# get spesific row
a[0,:]

array([1, 3, 5, 7, 9])

In [34]:
# get spesific column
a[:,4]

array([ 9, 10])

In [41]:
# getting little more fancy
a[1,0:-1:4]

array([2])

In [48]:
# change elemant
a[:,3]=[15,16]

**3-d examble**


In [52]:
c=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[2,5,8]]])
c

array([[[1, 2, 3],
        [4, 5, 6]],

       [[7, 8, 9],
        [2, 5, 8]]])

In [54]:
#get spesific elemant 
c[0,1,:]

array([4, 5, 6])

In [56]:
# replace
c[1,1,:]=[0,0,0]
c

array([[[1, 2, 3],
        [4, 5, 6]],

       [[7, 8, 9],
        [0, 0, 0]]])

**Initializing Different Types of Arrays**

In [60]:
# All zeros matrix
np.zeros((2,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [64]:
# All ones matrix
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [65]:
# Any other number
np.full((3,3),50)

array([[50, 50, 50],
       [50, 50, 50],
       [50, 50, 50]])

In [66]:
# Any other number (full like)
np.full_like(c,20)

array([[[20, 20, 20],
        [20, 20, 20]],

       [[20, 20, 20],
        [20, 20, 20]]])

In [70]:
# Random decimal numbers
np.random.rand(3,2)

array([[0.05957272, 0.29411839],
       [0.17891008, 0.26636403],
       [0.53779   , 0.05848279]])

In [77]:
# random inregers values
np.random.randint(10,15,size=(3,3))

array([[11, 10, 10],
       [13, 10, 13],
       [10, 10, 14]])

In [83]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [94]:
# repeat an array
arr=np.array([[1,2,3]])
ar1=np.repeat(arr,3,axis=0)
ar1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [116]:
v=np.full((5,5),1)
z=np.zeros((3,3))
v[1:4,1:4]=z
v[2,2]=9
print(v)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


**Be careful when copying arrays!!!**

In [123]:
a=np.array([1,2,3])
b=a.copy()
b[1]=100
a

array([1, 2, 3])

**Mathematics**

In [135]:
a=np.array([2,4,6])
a

array([2, 4, 6])

In [126]:
a+5

array([ 7,  9, 11])

In [129]:
a*2

array([ 4,  8, 12])

In [133]:
a+=2
a

array([14, 16, 18])

In [136]:
b=np.array([5,5,5])
a+b

array([ 7,  9, 11])

In [143]:
#take the sin
np.sin(a)

array([ 0.90929743, -0.7568025 , -0.2794155 ])

**Linear Algebra**

In [151]:
a=np.full((2,3),5)
b=np.ones((3,2))
np.matmul(a,b)

array([[15., 15.],
       [15., 15.]])

In [155]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

**Statistics**

In [163]:
s=np.array([[2,4,6,8,10],[1,3,5,7,9]])

In [171]:
np.sum(s,axis=1)

array([30, 25])

In [174]:
np.average(s,axis=1)

array([6., 5.])

**Reorganizing Arrays**

In [180]:
b=np.array([[1,3,5,7],[2,4,6,8]])
b
a=b.reshape((4,2))
a

array([[1, 3],
       [5, 7],
       [2, 4],
       [6, 8]])

In [186]:
# Vertically stacking vectors
v1=np.array([1,3,5,7])
v2=np.array([2,4,6,8])
np.vstack([v1,v2,v1])

array([[1, 3, 5, 7],
       [2, 4, 6, 8],
       [1, 3, 5, 7]])

In [200]:
# Horizontal stack
h1=np.zeros((3,3))
h2=np.ones((3,3))
np.hstack([h1,h2])

array([[0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.]])